sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env:
        - EXECUTE_CS_CHECK=true
        - EXECUTE_COVERAGE=true
    - php: 7
    - php: hhvm
  allow_failures:
    - php: 7

before_install:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then rm phpunit.xml; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then mv phpunit.hhvm.xml phpunit.xml; fi;'
  - if [[ $EXECUTE_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then composer require --no-update satooshi/php-coveralls:dev-master ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then composer require --no-update squizlabs/php_codesniffer:dev-master ; fi

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then ./bin/phpunit --coverage-clover clover.xml ; fi
  - if [[ $EXECUTE_COVERAGE != 'true' ]]; then ./bin/phpunit ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./bin/phpcs ; fi

after_script:
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then ./bin/coveralls ; fi